DROP TABLE store_business

CREATE TABLE store_business (
    business_number BIGINT,
    business_name VARCHAR(255),
    branch_name VARCHAR(255),
    large_category_code VARCHAR(10),
    large_category_name VARCHAR(50),
    medium_category_code VARCHAR(10),
    medium_category_name VARCHAR(50),
    small_category_code VARCHAR(10),
    small_category_name VARCHAR(50),
    industry_classification_code VARCHAR(10),
    industry_classification_name VARCHAR(100),
    city_code VARCHAR(10),
    city_name VARCHAR(50),
    district_code VARCHAR(10),
    district_name VARCHAR(50),
    administrative_dong_code VARCHAR(10),
    administrative_dong_name VARCHAR(50),
    legal_dong_code VARCHAR(10),
    legal_dong_name VARCHAR(50),
    lot_code VARCHAR(20),
    lot_division_code VARCHAR(10),
    lot_division_name VARCHAR(50),
    lot_main_number VARCHAR(20),
    lot_sub_number VARCHAR(20),
    lot_address VARCHAR(255),
    road_name_code VARCHAR(10),
    road_name VARCHAR(255),
    building_main_number VARCHAR(20),
    building_sub_number VARCHAR(20),
    building_management_number VARCHAR(50),
    building_name VARCHAR(255),
    road_name_address VARCHAR(255),
    old_postal_code VARCHAR(10),
    new_postal_code VARCHAR(10),
    dong_info VARCHAR(50),
    floor_info VARCHAR(50),
    room_info VARCHAR(50),
    longitude DECIMAL(15, 10),
    latitude DECIMAL(15, 10),
    quarter_year VARCHAR(7),  -- 분기별로 저장 (예: "2024-Q1")
    PRIMARY KEY (building_management_number, quarter_year)
);
