-- LOCAL_STORE 테이블에 인덱스 생성
CREATE INDEX idx_local_store_city_district_sub
ON LOCAL_STORE (CITY_ID, DISTRICT_ID, SUB_DISTRICT_ID);

-- CITY 테이블에 인덱스 생성
CREATE INDEX idx_city_id
ON CITY (CITY_ID);

-- DISTRICT 테이블에 인덱스 생성
CREATE INDEX idx_district_id
ON DISTRICT (DISTRICT_ID);

-- SUB_DISTRICT 테이블에 인덱스 생성
CREATE INDEX idx_sub_district_id
ON SUB_DISTRICT (SUB_DISTRICT_ID);
--

-- 외래 키 인덱스
CREATE INDEX idx_city_id ON `COMMERCIAL_DISTRICT` (`CITY_ID`);
CREATE INDEX idx_district_id ON `COMMERCIAL_DISTRICT` (`DISTRICT_ID`);
CREATE INDEX idx_sub_district_id ON `COMMERCIAL_DISTRICT` (`SUB_DISTRICT_ID`);
CREATE INDEX idx_biz_main_category_id ON `COMMERCIAL_DISTRICT` (`BIZ_MAIN_CATEGORY_ID`);
CREATE INDEX idx_biz_sub_category_id ON `COMMERCIAL_DISTRICT` (`BIZ_SUB_CATEGORY_ID`);
CREATE INDEX idx_biz_detail_category_id ON `COMMERCIAL_DISTRICT` (`BIZ_DETAIL_CATEGORY_ID`);

-- 자주 사용될 컬럼 인덱스
CREATE INDEX idx_market_size ON `COMMERCIAL_DISTRICT` (`MARKET_SIZE`);
CREATE INDEX idx_average_sales ON `COMMERCIAL_DISTRICT` (`AVERAGE_SALES`);
CREATE INDEX idx_operating_cost ON `COMMERCIAL_DISTRICT` (`OPERATING_COST`);
CREATE INDEX idx_food_cost ON `COMMERCIAL_DISTRICT` (`FOOD_COST`);
CREATE INDEX idx_employee_cost ON `COMMERCIAL_DISTRICT` (`AVERAGE_PAYMENT`); -- 평균 결제 인건비X
CREATE INDEX idx_rental_cost ON `COMMERCIAL_DISTRICT` (`RENTAL_COST`);
CREATE INDEX idx_average_profit ON `COMMERCIAL_DISTRICT` (`AVERAGE_PROFIT`);