-- 외래 키 제약 조건을 비활성화
SET
    FOREIGN_KEY_CHECKS = 0;

-- 테이블 삭제
DROP TABLE IF EXISTS `POPULATION`;

DROP TABLE IF EXISTS `LOC_INFO`;

DROP TABLE IF EXISTS `RISING_BUSINESS`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT`;

DROP TABLE IF EXISTS `BIZ_DETAIL_CATEGORY`;

DROP TABLE IF EXISTS `BIZ_SUB_CATEGORY`;

DROP TABLE IF EXISTS `BIZ_MAIN_CATEGORY`;

DROP TABLE IF EXISTS `SUB_DISTRICT`;

DROP TABLE IF EXISTS `DISTRICT`;

DROP TABLE IF EXISTS `CITY`;

-- 테이블 생성
CREATE TABLE
    `CITY` (
        `CITY_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_CID',
        `CITY_NAME` VARCHAR(50) NOT NULL COMMENT '시/도명',
        PRIMARY KEY (`CITY_ID`)
    );

CREATE TABLE
    `DISTRICT` (
        `DISTRICT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_DID',
        `CITY_ID` INT NOT NULL COMMENT 'FK_CID',
        `DISTRICT_NAME` VARCHAR(50) NOT NULL COMMENT '시/군/구명',
        PRIMARY KEY (`DISTRICT_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`)
    );

CREATE TABLE
    `SUB_DISTRICT` (
        `SUB_DISTRICT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_SDID',
        `CITY_ID` INT NOT NULL COMMENT 'FK_CID',
        `DISTRICT_ID` INT NOT NULL COMMENT 'FK_DID',
        `SUB_DISTRICT_NAME` VARCHAR(50) NULL COMMENT '읍/면/동 명',
        PRIMARY KEY (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`)
    );

CREATE TABLE
    `BIZ_MAIN_CATEGORY` (
        `BIZ_MAIN_CATEGORY_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_BMCID',
        `BIZ_MAIN_CATEGORY_NAME` VARCHAR(50) NULL COMMENT '비즈맵 대분류명',
        PRIMARY KEY (`BIZ_MAIN_CATEGORY_ID`)
    );

CREATE TABLE
    `BIZ_SUB_CATEGORY` (
        `BIZ_SUB_CATEGORY_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_BSCID',
        `BIZ_MAIN_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BMCID',
        `SUB_CATEGORY_NAME` VARCHAR(50) NULL COMMENT '비즈맵 중분류명',
        PRIMARY KEY (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`)
    );

CREATE TABLE
    `BIZ_DETAIL_CATEGORY` (
        `BIZ_DETAIL_CATEGORY_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_BDID',
        `BIZ_SUB_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BSCID',
        `DETAIL_CATEGORY` VARCHAR(50) NULL COMMENT '비즈맵 소분류명',
        PRIMARY KEY (`BIZ_DETAIL_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`)
    );

CREATE TABLE
    `COMMERCIAL_DISTRICT` (
        `COMMERCIAL_DISTRICT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_CDID',
        `CITY_ID` INT NOT NULL COMMENT 'FK_CID',
        `DISTRICT_ID` INT NOT NULL COMMENT 'FK_DID',
        `SUB_DISTRICT_ID` INT NOT NULL COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BDID',
        `NATIONAL_DENSITY` DECIMAL(5, 2) NULL COMMENT '전국 밀집도',
        `CITY_DENSITY` DECIMAL(5, 2) NULL COMMENT '시/도 밀집도',
        `DISTRICT_DENSITY` DECIMAL(5, 2) NULL COMMENT '시/군/구 밀집도',
        `SUB_DISTRICT_DENSITY` DECIMAL(5, 2) NULL COMMENT '읍/면/동 밀집도',
        `MARKET_SIZE` INT NULL COMMENT '시장 규모',
        `AVERAGE_SALES` INT NULL COMMENT '평균 매출',
        `AVERAGE_PAYMENT` INT NULL COMMENT '결재단가',
        `USAGE_COUNT` INT NULL COMMENT '이용건수',
        `OPERATING_COST` INT NULL COMMENT '영업비용',
        `FOOD_COST` INT NULL COMMENT '식재료비',
        `EMPLOYEE_COST` INT NULL COMMENT '교용인 인건비',
        `RENTAL_COST` INT NULL COMMENT '임차료',
        `TAX_COST` INT NULL COMMENT '세금',
        `FAMILY_EMPLOYEE_COST` INT NULL COMMENT '가족 종사자 인건비',
        `CEO_COST` INT NULL COMMENT '대표자 인건비',
        `ETC_COST` INT NULL COMMENT '기타 비용',
        `AVERAGE_PROFIT` INT NULL COMMENT '영업이익',
        `AVG_PROFIT_PER_MON` DECIMAL(5, 2) NULL COMMENT '평균 월요일 매출 비중',
        `AVG_PROFIT_PER_TUE` DECIMAL(5, 2) NULL COMMENT '평균 화요일 매출 비중',
        `AVG_PROFIT_PER_WED` DECIMAL(5, 2) NULL COMMENT '평균 수요일 매출 비중',
        `AVG_PROFIT_PER_THU` DECIMAL(5, 2) NULL COMMENT '평균 목요일 매출 비중',
        `AVG_PROFIT_PER_FRI` DECIMAL(5, 2) NULL COMMENT '평균 금요일 매출 비중',
        `AVG_PROFIT_PER_SAT` DECIMAL(5, 2) NULL COMMENT '평균 토요일 매출 비중',
        `AVG_PROFIT_PER_SUN` DECIMAL(5, 2) NULL COMMENT '평균 일요일 매출 비중',
        `AVG_PROFIT_PER_06_09` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중06_09',
        `AVG_PROFIT_PER_09_12` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중09_12',
        `AVG_PROFIT_PER_12_15` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중12_15',
        `AVG_PROFIT_PER_15_18` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중15_18',
        `AVG_PROFIT_PER_18_21` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중18_21',
        `AVG_PROFIT_PER_21_24` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중21_24',
        `AVG_PROFIT_PER_24_06` DECIMAL(5, 2) NULL COMMENT '시간별 매출 비중24_06',
        `AVG_CLIENT_PER_M_20` DECIMAL(5, 2) NULL COMMENT '남 20대 비중',
        `AVG_CLIENT_PER_M_30` DECIMAL(5, 2) NULL COMMENT '남 30대 비중',
        `AVG_CLIENT_PER_M_40` DECIMAL(5, 2) NULL COMMENT '남 40대 비중',
        `AVG_CLIENT_PER_M_50` DECIMAL(5, 2) NULL COMMENT '남 50대 비중',
        `AVG_CLIENT_PER_M_60` DECIMAL(5, 2) NULL COMMENT '남 60대 비중',
        `AVG_CLIENT_PER_F_20` DECIMAL(5, 2) NULL COMMENT '여 20대 비중',
        `AVG_CLIENT_PER_F_30` DECIMAL(5, 2) NULL COMMENT '여 30대 비중',
        `AVG_CLIENT_PER_F_40` DECIMAL(5, 2) NULL COMMENT '여 40대 비중',
        `AVG_CLIENT_PER_F_50` DECIMAL(5, 2) NULL COMMENT '여 50대 비중',
        `AVG_CLIENT_PER_F_60` DECIMAL(5, 2) NULL COMMENT '여 60대 비중',
        `TOP_MENU_1` VARCHAR(50) NULL COMMENT '뜨는 메뉴 TOP1',
        `TOP_MENU_2` VARCHAR(50) NULL COMMENT '뜨는 메뉴 TOP2',
        `TOP_MENU_3` VARCHAR(50) NULL COMMENT '뜨는 메뉴 TOP3',
        `TOP_MENU_4` VARCHAR(50) NULL COMMENT '뜨는 메뉴 TOP4',
        `TOP_MENU_5` VARCHAR(50) NULL COMMENT '뜨는 메뉴 TOP5',
        `CREATED_AT` DATETIME NOT NULL COMMENT '생성일시',
        `UPDATED_AT` DATETIME NOT NULL COMMENT '수정일시',
        PRIMARY KEY (`COMMERCIAL_DISTRICT_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE
    `RISING_BUSINESS` (
        `RISING_BUSINESS_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_RBID',
        `CITY_ID` INT NOT NULL COMMENT 'FK_CID',
        `DISTRICT_ID` INT NOT NULL COMMENT 'FK_DID',
        `SUB_DISTRICT_ID` INT NOT NULL COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BDID',
        `START_DATE` DATE NOT NULL COMMENT '창업일',
        `TOTAL_COST` INT NULL COMMENT '총 창업비용',
        `TOTAL_REVENUE` INT NULL COMMENT '총 수익',
        `TOTAL_PROFIT` INT NULL COMMENT '총 이익',
        `CREATED_AT` DATETIME NOT NULL COMMENT '생성일시',
        `UPDATED_AT` DATETIME NOT NULL COMMENT '수정일시',
        PRIMARY KEY (`RISING_BUSINESS_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE
    `LOC_INFO` (
        `LOC_INFO_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_LIID',
        `CITY_ID` INT NOT NULL COMMENT 'FK_CID',
        `DISTRICT_ID` INT NOT NULL COMMENT 'FK_DID',
        `SUB_DISTRICT_ID` INT NOT NULL COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID` INT NOT NULL COMMENT 'FK_BDID',
        `LOC_NAME` VARCHAR(100) NULL COMMENT '상호명',
        `LOC_ADDRESS` VARCHAR(200) NULL COMMENT '주소',
        `LOC_PHONE` VARCHAR(20) NULL COMMENT '전화번호',
        `LOC_TYPE` VARCHAR(50) NULL COMMENT '업종',
        `CREATED_AT` DATETIME NOT NULL COMMENT '생성일시',
        `UPDATED_AT` DATETIME NOT NULL COMMENT '수정일시',
        PRIMARY KEY (`LOC_INFO_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE
    `POPULATION` (
        `population_id` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_PID',
        `CITY_ID` INT NOT NULL COMMENT 'FK_CID',
        `DISTRICT_ID` INT NOT NULL COMMENT 'FK_DID',
        `SUB_DISTRICT_ID` INT NOT NULL COMMENT 'FK_SDID',
        `POPULATION_TOTAL` INT NULL COMMENT '총 인구수',
        `POPULATION_MALE` INT NULL COMMENT '남성 인구수',
        `POPULATION_FEMALE` INT NULL COMMENT '여성 인구수',
        `POPULATION_AGE_0_9` INT NULL COMMENT '0-9세 인구수',
        `POPULATION_AGE_10_19` INT NULL COMMENT '10-19세 인구수',
        `POPULATION_AGE_20_29` INT NULL COMMENT '20-29세 인구수',
        `POPULATION_AGE_30_39` INT NULL COMMENT '30-39세 인구수',
        `POPULATION_AGE_40_49` INT NULL COMMENT '40-49세 인구수',
        `POPULATION_AGE_50_59` INT NULL COMMENT '50-59세 인구수',
        `POPULATION_AGE_60_69` INT NULL COMMENT '60-69세 인구수',
        `POPULATION_AGE_70` INT NULL COMMENT '70세 이상 인구수',
        PRIMARY KEY (`population_id`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`)
    );

-- 외래 키 제약 조건을 다시 활성화
SET
    FOREIGN_KEY_CHECKS = 1;