-- 외래 키 제약 조건을 비활성화
SET
    FOREIGN_KEY_CHECKS = 0;

-- 테이블 삭제

DROP TABLE IF EXISTS `OWNER_INFO`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_SUB_DISTRICT_DENSITY_STATISTICS`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_AVERAGE_SALES_STATISTICS`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_AVERAGE_PAYMENT_STATISTICS`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_SUB_DISTRICT_MAIN_CATEGORY_DISTRIBUTION`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_SUB_DISTRICT_WEEKDAY_TIME_AVERAGE_PROFIT`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_USEAGE_COUNT_STATISTICS`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT_MARKET_SIZE_STATISTICS`;

DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT__WEIGHTED_AVERAGE`;

DROP TABLE IF EXISTS `LOCAL_STORE_IMAGE`;

DROP TABLE IF EXISTS `LOC_INFO_STATISTICS`;

DROP TABLE IF EXISTS `POPULATION_INFO_MZ_STATISTICS`;

-- 테이블 생성

CREATE TABLE 
    `OWNER_INFO` (
        `OWNER_INFO_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT 'PK_OIID',
        `GENDER_ID`	INT	NOT NULL	COMMENT 'PK_GID',
        `OWNER_NAME`	VARCHAR(15)	NOT NULL	COMMENT '점주 이름',
        `OWNER_BIRTH`	DATE	NOT NULL	COMMENT '점주 생년월일',
        `OWNER_ADDRESS`	VARCHAR(255)	NOT NULL	COMMENT '주소',
        `OWNER_MBTI`	VARCHAR(4)	NOT NULL	COMMENT 'MBTI',
        `OWNER_PHONE`	VARCHAR(13)	NOT NULL	COMMENT '전화번호',
        `OWNER_LAW`	VARCHAR(255)	NULL	COMMENT '정책',
        `OWNER_EDUCATION`	VARCHAR(255)	NULL	COMMENT '교육',
        `OWNER_FUNDS`	VARCHAR(255)	NULL	COMMENT '자금',
        `OWNER_CUNSULT`	VARCHAR(255)	NULL	COMMENT '컨설팅',
        `OWNER_TRAND`	VARCHAR(255)	NULL	COMMENT '트랜드',
        `OWNER_ESTATE`	VARCHAR(255)	NULL	COMMENT '부동산',
        `OWNER_INTERIOR`	VARCHAR(255)	NULL	COMMENT '인테리어',
        `OWNER_FRANCHISE`	VARCHAR(255)	NULL	COMMENT '프랜차이즈',
        `OWNER_EMPLOYEE`	VARCHAR(255)	NULL	COMMENT '직원',
        `OWNER_BUSINESS_EXPANSION`	VARCHAR(255)	NULL	COMMENT '사업확장',
        `OWNER_ADDITIONAL_INCOME`	VARCHAR(255)	NULL	COMMENT '추가 수입',
        `OWNER_PURCHASE_GOODS`	VARCHAR(255)	NULL	COMMENT '물품구매',
        `OWNER_STORE_OPERATION`	VARCHAR(255)	NULL	COMMENT '매장 운영',
        `OWNER_SATIFICATOIN_STORE_OPERATION`	VARCHAR(255)	NULL	COMMENT '만족도 - 매장 운영',
        `OWNER_SATIFICATION_SALES`	VARCHAR(255)	NULL	COMMENT '만족도 - 매출',
        `OWNER_SATIFICATION_SOCIAL_ATMOSPHERE`	VARCHAR(255)	NULL	COMMENT '만족도 - 사회 분위기',
        `OWNER_SATIFICATION_CONTENT`	VARCHAR(255)	NULL	COMMENT '만족도 - 컨텐츠',
        `OWNER_SNS`	VARCHAR(255)	NULL	COMMENT 'SNS',
        PRIMARY KEY (`OWNER_INFO_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT_SUB_DISTRICT_DENSITY_STATISTICS` (
        `CDSDDS_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDSDDS',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `MED_VAL`	FLOAT	NOT NULL	COMMENT '중간값',
        `STD_VAL`	FLOAT	NOT NULL	COMMENT '표준편차',
        `MAX_VAL`	FLOAT	NOT NULL	COMMENT '최대값',
        `MIN_VAL`	FLOAT	NOT NULL	COMMENT '최소값',
        `J_SCORE`	FLOAT	NOT NULL	COMMENT 'J_SCORE',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDSDDS_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT_AVERAGE_SALES_STATISTICS` (
        `CDASS_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDASS',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `MED_VAL`	FLOAT	NOT NULL	COMMENT '중간값',
        `STD_VAL`	FLOAT	NOT NULL	COMMENT '표준편차',
        `MAX_VAL`	FLOAT	NOT NULL	COMMENT '최대값',
        `MIN_VAL`	FLOAT	NOT NULL	COMMENT '최소값',
        `J_SCORE`	FLOAT	NOT NULL	COMMENT 'J_SCORE',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDASS_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT_AVERAGE_PAYMENT_STATISTICS` (
        `CDAPS_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDAPS',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `MED_VAL`	FLOAT	NOT NULL	COMMENT '중간값',
        `STD_VAL`	FLOAT	NOT NULL	COMMENT '표준편차',
        `MAX_VAL`	FLOAT	NOT NULL	COMMENT '최대값',
        `MIN_VAL`	FLOAT	NOT NULL	COMMENT '최소값',
        `J_SCORE`	FLOAT	NOT NULL	COMMENT 'J_SCORE',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDAPS_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );


CREATE TABLE 
    `COMMERCIAL_DISTRICT_SUB_DISTRICT_MAIN_CATEGORY_DISTRIBUTION` (
        `CDSDMCD_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDSDMCD',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDSDMCD_ID`),
        CONSTRAINT `FK_CDSDMCD_CITY` FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        CONSTRAINT `FK_CDSDMCD_DISTIRCT` FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        CONSTRAINT `FK_CDSDMCD_SUB_DISTRICT` FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        CONSTRAINT `FK_CDSDMCD_BIZ_MAIN_CATEGORY` FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT_SUB_DISTRICT_WEEKDAY_TIME_AVERAGE_PROFIT` (
        `CDSDWAP_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDSDWAP',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_PROFIT_PER_MON`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 월요일  매출 비중',
        `AVG_PROFIT_PER_TUE`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 화요일  매출 비중',
        `AVG_PROFIT_PER_WED`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 수요일  매출 비중',
        `AVG_PROFIT_PER_THU`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 목요일  매출 비중',
        `AVG_PROFIT_PER_FRI`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 금요일  매출 비중',
        `AVG_PROFIT_PER_SAT`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 토요일  매출 비중',
        `AVG_PROFIT_PER_SUN`	DECIMAL(5, 2)	NOT NULL	COMMENT '평균 일요일  매출 비중',
        `AVG_PROFIT_PER_06_09`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중06_09',
        `AVG_PROFIT_PER_09_12`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중09_12',
        `AVG_PROFIT_PER_12_15`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중12_15',
        `AVG_PROFIT_PER_15_18`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중15_18',
        `AVG_PROFIT_PER_18_21`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중18_21',
        `AVG_PROFIT_PER_21_24`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중21_24',
        `AVG_PROFIT_PER_24_06`	DECIMAL(5, 2)	NOT NULL	COMMENT '시간별 매출 비중24_06',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일시',
        PRIMARY KEY (`CDSDWAP_ID`),
        CONSTRAINT `FK_CDSDWAP_CITY` FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        CONSTRAINT `FK_CDSDWAP_DISTRICT` FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        CONSTRAINT `FK_CDSDWAP_SUB_DISTRICT` FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        CONSTRAINT `FK_CDSDWAP_BIZ_MAIN_CATEGORY` FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        CONSTRAINT `FK_CDSDWAP_BIZ_SUB_CATEGORY` FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        CONSTRAINT `FK_CDSDWAP_BIZ_DETAIL_CATEGORY` FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT_USEAGE_COUNT_STATISTICS` (
        `CDUCS_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDUCS',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `MED_VAL`	FLOAT	NOT NULL	COMMENT '중간값',
        `STD_VAL`	FLOAT	NOT NULL	COMMENT '표준편차',
        `MAX_VAL`	FLOAT	NOT NULL	COMMENT '최대값',
        `MIN_VAL`	FLOAT	NOT NULL	COMMENT '최소값',
        `J_SCORE`	FLOAT	NOT NULL	COMMENT 'J_SCORE',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDUCS_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT_MARKET_SIZE_STATISTICS` (
        `CDMSS_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDMSS',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `MED_VAL`	FLOAT	NOT NULL	COMMENT '중간값',
        `STD_VAL`	FLOAT	NOT NULL	COMMENT '표준편차',
        `MAX_VAL`	FLOAT	NOT NULL	COMMENT '최대값',
        `MIN_VAL`	FLOAT	NOT NULL	COMMENT '최소값',
        `J_SCORE`	FLOAT	NOT NULL	COMMENT 'J_SCORE',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDMSS_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE 
    `COMMERCIAL_DISTRICT__WEIGHTED_AVERAGE` (
        `CDWA_ID`	INT	NOT NULL AUTO_INCREMENT	COMMENT 'PK_CDWA',
        `CITY_ID`	INT	NOT NULL	COMMENT 'FK_CID',
        `DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_DID',
        `SUB_DISTRICT_ID`	INT	NOT NULL	COMMENT 'FK_SDID',
        `BIZ_MAIN_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BMCID',
        `BIZ_SUB_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BSCID',
        `BIZ_DETAIL_CATEGORY_ID`	INT	NOT NULL	COMMENT 'FK_BDID',
        `AVG_VAL`	FLOAT	NOT NULL	COMMENT '평균',
        `STAT_LEVEL`	VARCHAR(10)	NOT NULL	COMMENT '참조레벨',
        `REF_DATE`	DATE	NOT NULL	COMMENT '기준년월',
        `CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성날짜',
        PRIMARY KEY (`CDWA_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`),
        FOREIGN KEY (`BIZ_MAIN_CATEGORY_ID`) REFERENCES `BIZ_MAIN_CATEGORY` (`BIZ_MAIN_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_SUB_CATEGORY_ID`) REFERENCES `BIZ_SUB_CATEGORY` (`BIZ_SUB_CATEGORY_ID`),
        FOREIGN KEY (`BIZ_DETAIL_CATEGORY_ID`) REFERENCES `BIZ_DETAIL_CATEGORY` (`BIZ_DETAIL_CATEGORY_ID`)
    );

CREATE TABLE 
    `LOCAL_STORE_IMAGE` (
        `LOCAL_STORE_IMAGE_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT 'PK_LSIID',
        `STORE_BUSINESS_NUMBER`	VARCHAR(100)	NOT NULL	COMMENT 'FK_RID',
        `LOCAL_STORE_IMAGE_URL`	VARCHAR(255)	NOT NULL	COMMENT '매장 이미지 URL',
        PRIMARY KEY (`LOCAL_STORE_IMAGE_ID`)
    );

CREATE TABLE
    `LOC_INFO_STATISTICS` (
        `LOC_INFO__STAT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_LISID',
        `CITY_ID` INT NULL COMMENT 'PK_CID',
        `DISTRICT_ID` INT NULL COMMENT 'PK_DID',
        `SUB_DISTRICT_ID` INT NULL COMMENT 'PK_SDID',
        `REFERENCE_ID` INT NOT NULL COMMENT 'PK_RFID',
        `TARGET_ITEM` VARCHAR(50) NOT NULL COMMENT '통계 낼 항목',
        `AVG_VAL` FLOAT NULL COMMENT '평균',
        `MED_VAL` FLOAT NULL COMMENT '중간값',
        `STD_VAL` FLOAT NULL COMMENT '표준편차',
        `MAX_VAL` FLOAT NULL COMMENT '최대값',
        `MIN_VAL` FLOAT NULL COMMENT '최소값',
        `J_SCORE_RANK` FLOAT NULL COMMENT 'J_SCORE_RANK',
        `J_SCORE_PER` FLOAT NULL COMMENT 'J_SCORE_PER',
        `J_SCORE` FLOAT NULL COMMENT 'J_SCORE',
        `J_SCORE_PER_NON_OUTLIERS` FLOAT NULL COMMENT 'J_SCORE_PER 이상치제거',
        `J_SCORE_NON_OUTLIERS` FLOAT NULL COMMENT 'J_SCORE 이상치제거',
        `REF_DATE` DATE NULL COMMENT '기준 데이터 날짜',
        `STAT_LEVEL` VARCHAR(10) NULL COMMENT '참조 레벨',
        `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
        PRIMARY KEY (`LOC_INFO_STAT_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`)
    );


CREATE TABLE
    `POPULATION_INFO_MZ_STATISTICS` (
        `POP_INFO_MZ_STAT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK_PIMSID',
        `CITY_ID` INT NULL COMMENT 'PK_CID',
        `DISTRICT_ID` INT NULL COMMENT 'PK_DID',
        `SUB_DISTRICT_ID` INT NULL COMMENT 'PK_SDID',
        `AVG_VAL` FLOAT NULL COMMENT '평균',
        `MED_VAL` FLOAT NULL COMMENT '중간값',
        `STD_VAL` FLOAT NULL COMMENT '표준편차',
        `MAX_VAL` FLOAT NULL COMMENT '최대값',
        `MIN_VAL` FLOAT NULL COMMENT '최소값',
        `J_SCORE_RANK` FLOAT NULL COMMENT 'J_SCORE_RANK',
        `J_SCORE_PER` FLOAT NULL COMMENT 'J_SCORE_PER',
        `J_SCORE` FLOAT NULL COMMENT 'J_SCORE',
        `J_SCORE_PER_NON_OUTLIERS` FLOAT NULL COMMENT 'J_SCORE_PER 이상치제거',
        `J_SCORE_NON_OUTLIERS` FLOAT NULL COMMENT 'J_SCORE 이상치제거',
        `REF_DATE` DATE NULL COMMENT '기준 데이터 날짜',
        `STAT_LEVEL` VARCHAR(10) NULL COMMENT '참조 레벨',
        `CREATED_AT` TIMESTAMP NULL COMMENT '생성일시',
        PRIMARY KEY (`POP_INFO_MZ_STAT_ID`),
        FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`CITY_ID`),
        FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`DISTRICT_ID`),
        FOREIGN KEY (`SUB_DISTRICT_ID`) REFERENCES `SUB_DISTRICT` (`SUB_DISTRICT_ID`)
    );

-- 외래 키 제약 조건을 다시 활성화
SET
    FOREIGN_KEY_CHECKS = 1;