-- 제약 조건 해제
SET FOREIGN_KEY_CHECKS = 0;

-- 기존 테이블 삭제
DROP TABLE IF EXISTS `REGION`;
DROP TABLE IF EXISTS `POPULATION`;
DROP TABLE IF EXISTS `RISING_BUSINESS`;
DROP TABLE IF EXISTS `CATEGORY`;
DROP TABLE IF EXISTS `POPINFO`;
DROP TABLE IF EXISTS `SHOP`;
DROP TABLE IF EXISTS `COMMERCIAL_DISTRICT`;
DROP TABLE IF EXISTS `PSHOP`;
DROP TABLE IF EXISTS `PSHOPDETAIL`;

-- 새 테이블 생성
CREATE TABLE `REGION` (
    `REGION_ID` INT NOT NULL AUTO_INCREMENT COMMENT '지역 ID (PK)',
    `CITY` VARCHAR(50) NOT NULL COMMENT '시/도',
    `DISTRICT` VARCHAR(50) NOT NULL COMMENT '시/군/구',
    `SUB_DISTRICT` VARCHAR(50) NOT NULL COMMENT '읍/면/동',
    PRIMARY KEY (`REGION_ID`)
);

CREATE TABLE `POPULATION` (
    `POP_ID` INT NOT NULL AUTO_INCREMENT COMMENT '인구 데이터 ID (PK)',
    `ID` INT NOT NULL COMMENT '지역 ID (FK)',
    `GENDER` VARCHAR(9) NOT NULL COMMENT '성별',
    `0TO9` INT NOT NULL COMMENT '0대 인구',
    `10TO19` INT NOT NULL COMMENT '10대 인구',
    `20TO29` INT NOT NULL COMMENT '20대 인구',
    `30TO39` INT NOT NULL COMMENT '30대 인구',
    `40TO49` INT NOT NULL COMMENT '40대 인구',
    `50TO59` INT NOT NULL COMMENT '50대 인구',
    `60TO69` INT NOT NULL COMMENT '60대 인구',
    `70TO79` INT NOT NULL COMMENT '70대 인구',
    `80TO89` INT NOT NULL COMMENT '80대 인구',
    `90TO99` INT NOT NULL COMMENT '90대 인구',
    `100TO109` INT NOT NULL COMMENT '100대 인구',
    `TOTAL` INT NOT NULL COMMENT '총인구',
    `MALETOTAL` INT NOT NULL COMMENT '남자 총인구',
    `FEMALETOTAL` INT NOT NULL COMMENT '여자 총인구',
    `Y_M` INT NOT NULL COMMENT '기준 년월',
    PRIMARY KEY (`POP_ID`),
    FOREIGN KEY (`ID`) REFERENCES `REGION` (`REGION_ID`)
);

CREATE TABLE `RISING_BUSINESS` (
    `RISING_BUSINESS_ID` INT NOT NULL AUTO_INCREMENT COMMENT '상승 비즈니스 ID (PK)',
    `REGION_ID` INT NOT NULL COMMENT '지역 ID (FK)',
    `BUSINESS_NAME` VARCHAR(50) COMMENT '비즈니스 이름',
    `GROWTH_RATE` DECIMAL(7, 2) COMMENT '성장률',
    `SUB_DISTRICT_RANK` INT COMMENT '해당 구역의 순위',
    PRIMARY KEY (`RISING_BUSINESS_ID`),
    FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`REGION_ID`)
);

CREATE TABLE `CATEGORY` (
    `CATEGORY_ID` INT NOT NULL AUTO_INCREMENT COMMENT '카테고리 ID (PK)',
    `MAIN_CATEGORY` VARCHAR(50) NOT NULL COMMENT '대분류',
    `SUB_CATEGORY` VARCHAR(50) NOT NULL COMMENT '중분류',
    `DETAIL_CATEGORY` VARCHAR(50) NOT NULL COMMENT '세분류',
    PRIMARY KEY (`CATEGORY_ID`)
);

CREATE TABLE `POPINFO` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '정보 ID (PK)',
    `REGION_ID` INT NOT NULL COMMENT '지역 ID (FK)',
    `BUIS` INT COMMENT '업소 수',
    `MOVEPOP` INT COMMENT '유동인구',
    `SALE` INT COMMENT '매출',
    `WORKPOP` INT COMMENT '직장인구',
    `EARN` INT COMMENT '소득',
    `SPEND` INT COMMENT '소비',
    `HOMEPOP` INT COMMENT '세대수',
    `YEAR_MONTH` INT NOT NULL COMMENT '년월',
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`REGION_ID`)
);

CREATE TABLE `SHOP` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '상점 ID (PK)',
    `REGION_ID` INT NOT NULL COMMENT '지역 ID (FK)',
    `NAME` VARCHAR(300) COMMENT '상호명',
    `SPOT` VARCHAR(300) COMMENT '지점명',
    `LANDCATEGORY` VARCHAR(30) COMMENT '대지 유형',
    `ROADNAME` VARCHAR(255) COMMENT '도로명',
    `YEAR_MONTH` INT NOT NULL COMMENT '년월',
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`REGION_ID`)
);

CREATE TABLE `COMMERCIAL_DISTRICT` (
    `COMMERCIAL_DISTRICT_ID` INT NOT NULL AUTO_INCREMENT COMMENT '상업 지구 ID (PK)',
    `REGION_ID` INT NOT NULL COMMENT '지역 ID (FK)',
    `CATEGORY_ID` INT NOT NULL COMMENT '카테고리 ID (FK)',
    `NATIONAL_DENSITY` DECIMAL(5, 2) COMMENT '전국 밀도',
    `CITY_DENSITY` DECIMAL(5, 2) COMMENT '도시 밀도',
    `DISTRICT_DENSITY` DECIMAL(5, 2) COMMENT '구 밀도',
    `SUB_DISTRICT_DENSITY` DECIMAL(5, 2) COMMENT '동 밀도',
    `MARKET_SIZE` INT COMMENT '시장 규모',
    `AVERAGE_SALES` INT COMMENT '평균 매출',
    `AVERAGE_PAYMENT` INT COMMENT '평균 결제액',
    `USAGE_COUNT` INT COMMENT '사용 횟수',
    `OPERATING_COST` INT COMMENT '운영 비용',
    `FOOD_COST` INT COMMENT '식품 비용',
    `EMPLOYEE_COST` INT COMMENT '직원 비용',
    `RENTAL_COST` INT COMMENT '임대 비용',
    `TAX_COST` INT COMMENT '세금 비용',
    `FAMILY_EMPLOYEE_COST` INT COMMENT '가족 직원 비용',
    `CEO_COST` INT COMMENT 'CEO 비용',
    `ETC_COST` INT COMMENT '기타 비용',
    `AVERAGE_PROFIT` INT COMMENT '평균 이익',
    `AVG_PROFIT_PER_MON` DECIMAL(5, 2) COMMENT '월 평균 이익',
    `AVG_PROFIT_PER_TUES` DECIMAL(5, 2) COMMENT '화 평균 이익',
    `AVG_PROFIT_PER_WED` DECIMAL(5, 2) COMMENT '수 평균 이익',
    `AVG_PROFIT_PER_THU` DECIMAL(5, 2) COMMENT '목 평균 이익',
    `AVG_PROFIT_PER_FRI` DECIMAL(5, 2) COMMENT '금 평균 이익',
    `AVG_PROFIT_PER_SAT` DECIMAL(5, 2) COMMENT '토 평균 이익',
    `AVG_PROFIT_PER_SUN` DECIMAL(5, 2) COMMENT '일 평균 이익',
    `AVG_PROFIT_PER_06_09` DECIMAL(5, 2) COMMENT '06-09 평균 이익',
    `AVG_PROFIT_PER_09_12` DECIMAL(5, 2) COMMENT '09-12 평균 이익',
    `AVG_PROFIT_PER_12_15` DECIMAL(5, 2) COMMENT '12-15 평균 이익',
    `AVG_PROFIT_PER_15_18` DECIMAL(5, 2) COMMENT '15-18 평균 이익',
    `AVG_PROFIT_PER_18_21` DECIMAL(5, 2) COMMENT '18-21 평균 이익',
    `AVG_PROFIT_PER_21_24` DECIMAL(5, 2) COMMENT '21-24 평균 이익',
    `AVG_CLIENT_PER_M_20` DECIMAL(5, 2) COMMENT '20대 남성 평균 고객',
    `AVG_CLIENT_PER_M_30` DECIMAL(5, 2) COMMENT '30대 남성 평균 고객',
    `AVG_CLIENT_PER_M_40` DECIMAL(5, 2) COMMENT '40대 남성 평균 고객',
    `AVG_CLIENT_PER_M_50` DECIMAL(5, 2) COMMENT '50대 남성 평균 고객',
    `AVG_CLIENT_PER_M_60` DECIMAL(5, 2) COMMENT '60대 남성 평균 고객',
    `AVG_CLIENT_PER_F_20` DECIMAL(5, 2) COMMENT '20대 여성 평균 고객',
    `AVG_CLIENT_PER_F_30` DECIMAL(5, 2) COMMENT '30대 여성 평균 고객',
    `AVG_CLIENT_PER_F_40` DECIMAL(5, 2) COMMENT '40대 여성 평균 고객',
    `AVG_CLIENT_PER_F_50` DECIMAL(5, 2) COMMENT '50대 여성 평균 고객',
    `AVG_CLIENT_PER_F_60` DECIMAL(5, 2) COMMENT '60대 여성 평균 고객',
    `TOP_MENU_1` VARCHAR(50) COMMENT '주요 메뉴 1',
    `TOP_MENU_2` VARCHAR(50) COMMENT '주요 메뉴 2',
    `TOP_MENU_3` VARCHAR(50) COMMENT '주요 메뉴 3',
    PRIMARY KEY (`COMMERCIAL_DISTRICT_ID`),
    FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`REGION_ID`),
    FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`)
);

CREATE TABLE `PSHOP` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '업소 ID (PK)',
    `CATEGORY_ID` INT NOT NULL COMMENT '카테고리 ID (FK)',
    `SUB_DISTRICT` VARCHAR(100) COMMENT '동',
    `ADDRESS` VARCHAR(300) COMMENT '주소',
    `COORDINATES` POINT COMMENT '좌표',
    `OPENING_DATE` DATE COMMENT '개업일',
    `CLOSE_DATE` DATE COMMENT '폐업일',
    `STATUS` ENUM('OPEN', 'CLOSED') COMMENT '상태',
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`)
);

CREATE TABLE `PSHOPDETAIL` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '상점 세부 정보 ID (PK)',
    `PSHOP_ID` INT NOT NULL COMMENT '업소 ID (FK)',
    `MONTH` DATE COMMENT '월',
    `TOTAL_SALES` INT COMMENT '총 매출',
    `COST` INT COMMENT '비용',
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`PSHOP_ID`) REFERENCES `PSHOP` (`ID`)
);



-- 제약 조건 설정
SET FOREIGN_KEY_CHECKS = 1;
